//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientNote
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Username { get; set; }
        public string Category { get; set; }
    }
}
