//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int Id { get; set; }
        public Nullable<double> CommAmtDue { get; set; }
        public Nullable<double> DisbReqAmount { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> DisbPaidDate { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> DisbPaid { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> CommRequestedDate { get; set; }
        public string Username { get; set; }
        public string Description { get; set; }
    }
}
