//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementRequest
    {
        public int Id { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<double> CommissionsDue { get; set; }
        public Nullable<double> DisbursementRequested { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Username { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string Approver { get; set; }
    }
}
