//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNum { get; set; }
        public string ShipToAddress { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string Email { get; set; }
        public string AssignedTo { get; set; }
        public string JobType { get; set; }
        public string JobSubType { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string PONumber { get; set; }
        public string Status { get; set; }
        public Nullable<double> JobCosts { get; set; }
        public string InsClaimNum { get; set; }
        public Nullable<bool> InsSupplement { get; set; }
        public string InsInsuranceCarrier { get; set; }
        public string InsPhone { get; set; }
        public string InsExtension { get; set; }
        public string InsAdjusterField { get; set; }
        public string InsAdjusterDesk { get; set; }
        public string InsEmail { get; set; }
        public string InsFax { get; set; }
        public string PaymentType { get; set; }
        public Nullable<double> GrossProfit { get; set; }
        public Nullable<double> OverheadCosts { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<bool> TruedUp { get; set; }
        public Nullable<System.DateTime> LastTrueUpDate { get; set; }
        public string LastTrueUpPerson { get; set; }
        public Nullable<double> CommissionBalance { get; set; }
        public Nullable<double> ContractAmount { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> LeadID { get; set; }
        public string PaymentNotes { get; set; }
        public Nullable<double> CommissionPercentage { get; set; }
        public string CoClient { get; set; }
        public string PermitNo { get; set; }
    }
}
