//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNum { get; set; }
        public string ShipToAddress { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string Email { get; set; }
        public string AssignedTo { get; set; }
        public string LeadType { get; set; }
        public string LeadStatus { get; set; }
        public string LeadSource { get; set; }
        public string LeadSubSource { get; set; }
        public string LeadCreator { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public Nullable<System.DateTime> JobCreationDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Username { get; set; }
        public string CoClient { get; set; }
        public string LeadSubType { get; set; }
    }
}
