//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeekViewEntities : DbContext
    {
        public PeekViewEntities()
            : base("name=PeekViewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientNote> ClientNotes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientSubType> ClientSubTypes { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<Commission> Commissions { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DisbursementRequest> DisbursementRequests { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompanies { get; set; }
        public virtual DbSet<JobExpens> JobExpenses { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobStatu> JobStatus { get; set; }
        public virtual DbSet<JobSubType> JobSubTypes { get; set; }
        public virtual DbSet<JobTrade> JobTrades { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<LeadSource> LeadSources { get; set; }
        public virtual DbSet<LeadStatusType> LeadStatusTypes { get; set; }
        public virtual DbSet<PaymentsDue> PaymentsDues { get; set; }
        public virtual DbSet<PaymentsReceived> PaymentsReceiveds { get; set; }
        public virtual DbSet<RoofAccessType> RoofAccessTypes { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<TradeBrandType> TradeBrandTypes { get; set; }
        public virtual DbSet<TradeColorStyle> TradeColorStyles { get; set; }
        public virtual DbSet<TradeSchedule> TradeSchedules { get; set; }
        public virtual DbSet<TradeStatusType> TradeStatusTypes { get; set; }
        public virtual DbSet<TradeType> TradeTypes { get; set; }
        public virtual DbSet<ZIPCode> ZIPCodes { get; set; }
    }
}
