//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Component { get; set; }
        public string Severity { get; set; }
        public string Message { get; set; }
        public string Stacktrace { get; set; }
    }
}
