//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeBrandType
    {
        public int Id { get; set; }
        public string TextValue { get; set; }
        public string RorC { get; set; }
        public string TradeType { get; set; }
        public string TradeSubType { get; set; }
    }
}
