//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peek.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeSchedule
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int LeadId { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> DateToStart { get; set; }
        public Nullable<System.DateTime> DateToEnd { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public string Status { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CoClient { get; set; }
        public Nullable<int> JobTradeId { get; set; }
    }
}
